---
- name: Sync pacman database
  pacman:
    update_cache: yes
  changed_when: false

- name: Ensure aur_builder exists
  user:
    name: aur_builder
    group: wheel

- name: Add aur_builder to sudo file for AUR tasks
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
